### ISSUE TITLE
Give Lucy admin permission

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [ONSdigital/sdg-featbranch#2]
@SavvasStephanides Hope your new role is going well! Can you give me admin permissions to this repo please?

**Comment by SavvasStephanides** [comment]
Hi Lucy! New role is great thanks! Unfortunately, I don't have the rights to add admin permissions to ONSDigital repos. Can you ask [any of these people with org permissions](https://github.com/orgs/ONSdigital/people) to do this?

**Comment by LucyGwilliamAdmin** [comment]
@SavvasStephanides glad to hear! Thanks for sending over list of people 👍

**Comment by LucyGwilliamAdmin** [comment]
@bambrp @bkhan2 @insacuri can one of you give me admin access to this repo please?

**Comment by LucyGwilliamAdmin** [comment]
@insacuri @jdfox @warrenbailey @jterryons @bkhan2 @bambrp 

Hi all, could one of you give me admin access to this repository please? Savvas set it up but is no longer on the team

**Comment by LucyGwilliamAdmin** [comment]
I now have admin permission so closing. Thanks all though!
