### ISSUE TITLE
Reconnect with slack

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [ONSdigital/sdg-featbranch#3]
When Savvas was removed from ONS Slack, the FeatureBranchBot integration was removed meaning we're no longer getting alerts once feature branches have been built.

Need to add the integration back in

**Comment by LucyGwilliamAdmin** [comment]
@SavvasStephanides wondering if you could give any pointers on how to do this please? hope all is well with you!

**Comment by SavvasStephanides** [comment]
Hey @LucyGwilliamAdmin! I hope everything is well with you!

I wasn't aware the Slack messages would stop!

First thing to do is to create a "Slack App". See [here](https://api.slack.com/apps?new_app=1). This will give you a "webhook" which is just a URL.

You'll then need to update the webhook in the server. For this you'll need to log in to the server and update the settings. If I remember well, once you log in you can run `~/.featbranch/settings/slackWebhook > "<YOUR_NEW_WEBHOOK>"` and it will update.

Let me know if it works.

**Comment by LucyGwilliamAdmin** [comment]
Thanks for the help!

I've just given this a go:

Is this where I should get the webhook from?
![image](https://user-images.githubusercontent.com/43404358/100349623-a574b100-2fe0-11eb-95c0-8ec046a5520d.png)

When I run `~/.featbranch/settings/slackWebhook > "<NEW_WEBHOOK>"` with that webhook I get this error:
-bash: <NEW_WEBHOOK>: No such file or directory

**Comment by LucyGwilliamAdmin** [comment]
Also just to clarify the URL in the sample curl isn't active webhook

**Comment by SavvasStephanides** [comment]
@LucyGwilliamAdmin The long URL starting with `https://hooks.slack.com...` is your webhook.

Sorry I wrote the wrong command before. Try this:

```bash
echo "<WEBHOOK>" > ~/.featbranch/settings/slackWebhook
```

**Comment by LucyGwilliamAdmin** [comment]
Ah great - so no error now 👍 

Just waiting to see if messages are going to post - do I need to restart the server or anything for the changes to be applied?

**Comment by SavvasStephanides** [comment]
I don't think so. But in case it doesn't work, maybe a restart will help

**Comment by LucyGwilliamAdmin** [comment]
Ah perfect - that worked. Thanks for all your help!
