### ISSUE TITLE
install.sh settings

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [ONSdigital/sdg-featbranch#6]
@SavvasStephanides

Really sorry to bother you...

I'm trying to use install.sh but I'm not sure of the user input needed e.g. here:
https://github.com/ONSdigital/sdg-featbranch/blob/master/install.sh#L11

**Comment by SavvasStephanides** [comment]
Hey! No problem at all! That’d be the profile that has the site and data repos (ONSdigital)

**Comment by LucyGwilliamAdmin** [comment]
Thanks Savvas!
